### ISSUE TITLE
[Feature] Excel Style navigation

### ISSUE THREAD

**Issue by PluggPreagar** [internet4refugees/beherbergung#106]
**Problem**
Navigating by TAB and ENTER is different from "Excel-Standard"

**Suggested solution**
Enter is not only supposed to go to next line. It is supposed to move to column where EDIT-Mode was started too. The idea is to allow fast entry of x-successive columns in multiple rows.

**Alternatives you've considered**

**Workaround**
- none 

**Urgency**
low priority

**Comment by johannesloetzsch** [comment]
I think TAB and ENTER do allow quick editing.
TAB moves to the next column (same row) and ENTER moves to next row (same column).
In both cases, it will stay in edit-mode. 

At least this is how it the browsers I've tested. Does it behave different for you @PluggPreagar?

The only related bug I'm aware of is that ESC interrupts editing without saving for string-columns, but in boolean-columns the changed value is always saved. This is probably caused by the custom renderer for the checkboxes.

**Comment by PluggPreagar** [comment]
We are probably misunderstand us here.

The thing is - in Excel (etc.) ENTER not just moves i row down, it jumps back to first-edit-column. This allows to enter "a1"-TAB-"b1"-ENTER-"a2"-TAB-"b2"-ENTER-ESC to fill multiple columns in multiple rows in 1 go. Fast users will urge for that. ;-)

**Comment by johannesloetzsch** [comment]
ok, understood.

For the current usecase, I don't- consider this being relevant.
The most common way how users edit is:
1. one row (when correcting a dataset), that works with TAB
2. changing the same columns for different filtered rows, that works with ENTER with the current behavior

For editing multiple columns in multiple rows, I don't see a usecase in the current domain. In my opinion it is not relevant now.
If we change the software for other purposes and users request this feature, we can reopen this feature request.
